[package]
name = "klein"
version = "0.1.0"
authors = ["Lain-dono <lain.dono@gmail.com>"]
edition = "2018"

[dependencies]
wide = "0.4.3"

[dev-dependencies]
approx = "0.3.2"

[package.metadata.docs.rs]
rustdoc-args = ["--html-in-header", ".cargo/katex.html"]